### ISSUE TITLE
cpabe.java has no main method so do we have to create it on our own or there is another method for running it

### ISSUE THREAD

**Issue by harshdabas1** [TU-Berlin-SNET/jTR-ABE#2]
cpabe.java has no main method so do we have to create a method on our own or there is another method for running it.

**Comment by drkt** [comment]
/src/main/java/trabe/demo/DemoForCpabe.java

Best Regards

**Comment by harshdabas1** [comment]
Sir could you please list steps how to run the toolkit.
Please share an example to make it lot easier for me to understand.

**Comment by drkt** [comment]
Hello harsh dabas,

what do you mean by toolkit? Bethencourt uses the term toolkit for the ABE system methods _setup_, _keygen_, _encrypt_, _decrypt_ etc...
https://www.cs.utexas.edu/~bwaters/publications/papers/cp-abe.pdf

Liu's scheme is working in a similar way (compared to Bethencourt's cpabe) but it is more complex. In addition Liu provides a _trace_ method. However, he describes the mathematics in far more details! Which was helpful for the implementation (see the paper linked below).

Have you checked the already mentioned DemoForCpabe.java file in the  "demo" folder? 
What is unclear to you here?
This file shows an example "main method" and a utilisation of the cpabe.java library. 

Furthermore, the Lw14Test.java in the "tests" folder could be of help / be a starting point for diving into the code. 

If you are new "Attribute-based Encryption" I would recommend to start over with a more lightweight ABE scheme and implementation.

More background and method descriptions are available for download here: http://eprint.iacr.org/2014/616.pdf 
Methods and its arguments are explained (among others) on page 5 to 15.

Best Regards,

**Comment by nikunjm1010** [comment]
Sir it is as we are running a particular example ....its not general for example making our own example and we are making our own attributes and our own policy and then doing the process of encryption and decryption.

**Comment by nikunjm1010** [comment]
I need help about the performance of this scheme.Is it better than other revocation schemes like the piratte and if there is any comparison done on this scheme with other abe schemes.

**Comment by artjomb** [comment]
@nikunjm1010 This implementation uses JPBC in order to interface with the native C library. There are two ways you can run it: 
- pure Java implementation of the pairing and all of the curve operations (_slow_)
- enable the C wrapper for the native PBC library in which case the JPBC is only a proxy for those calls (_fast_).

We don't know if the performance of jTR-ABE with enabled C wrapper is comparable to an implementation of the same scheme purely in C by using the PBC library. It could be the same, but it doesn't have to be. 

Since I don't know of a JPBC implementation of PIRATTE (I only know of a C implementation), I would say that you first have to either:
- implement TR-ABE with pure PBC in C _or_
- implement PIRATTE in JPBC in Java

Otherwise, you won't have comparable results.

**Comment by nikunjm1010** [comment]
Thanks 😊

**Comment by harshdabas1** [comment]
Sir,how can i run the toolkit and create my own policy.
Can you list the commands which one may use to encrypt decrypt and keygen.

**Comment by artjomb** [comment]
@harshdabas1 You can easily change the policy string in the DemoForCpabe.java file and the run it. Remember that this repository only provides a Java library for Attribute-based Encryption. It **does not** give you a commandline tool or an attribute authority server to play around with. If you want that, you will have to build them yourself. 

You can start by changing the DemoForCpabe.java file to your liking and then use Maven to recompile and to run that class.

**Comment by harshdabas1** [comment]
Sir basically what i am trying to achieve is to find the time of
keygen,encryption and decryption with number of attributes like(5,10,15).
So how could i compute that?
